# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui',
# licensing of 'MainWindow.ui' applies.
#
# Created: Sat May  7 14:36:24 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 514)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.combo_name = QtWidgets.QComboBox(self.frame)
        self.combo_name.setObjectName("combo_name")
        self.horizontalLayout_3.addWidget(self.combo_name)
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.combo_baudrate = QtWidgets.QComboBox(self.frame)
        self.combo_baudrate.setObjectName("combo_baudrate")
        self.horizontalLayout_3.addWidget(self.combo_baudrate)
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.combo_bytesize = QtWidgets.QComboBox(self.frame)
        self.combo_bytesize.setObjectName("combo_bytesize")
        self.horizontalLayout_3.addWidget(self.combo_bytesize)
        self.label_4 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.combo_parity = QtWidgets.QComboBox(self.frame)
        self.combo_parity.setObjectName("combo_parity")
        self.horizontalLayout_3.addWidget(self.combo_parity)
        self.label_5 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.combo_stopsize = QtWidgets.QComboBox(self.frame)
        self.combo_stopsize.setObjectName("combo_stopsize")
        self.horizontalLayout_3.addWidget(self.combo_stopsize)
        self.btn_open = QtWidgets.QPushButton(self.frame)
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout_3.addWidget(self.btn_open)
        self.btn_close = QtWidgets.QPushButton(self.frame)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_3.addWidget(self.btn_close)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txt_send = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txt_send.setObjectName("txt_send")
        self.verticalLayout_2.addWidget(self.txt_send)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 75))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_4.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.radio_send_text_mode = QtWidgets.QRadioButton(self.frame_4)
        self.radio_send_text_mode.setObjectName("radio_send_text_mode")
        self.verticalLayout_7.addWidget(self.radio_send_text_mode)
        self.radio_send_hex_mode = QtWidgets.QRadioButton(self.frame_4)
        self.radio_send_hex_mode.setObjectName("radio_send_hex_mode")
        self.verticalLayout_7.addWidget(self.radio_send_hex_mode)
        self.radio_send_doublebyte = QtWidgets.QRadioButton(self.frame_4)
        self.radio_send_doublebyte.setObjectName("radio_send_doublebyte")
        self.verticalLayout_7.addWidget(self.radio_send_doublebyte)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_send_data = QtWidgets.QPushButton(self.frame_3)
        self.btn_send_data.setObjectName("btn_send_data")
        self.gridLayout.addWidget(self.btn_send_data, 1, 1, 1, 1)
        self.btn_send_clear = QtWidgets.QPushButton(self.frame_3)
        self.btn_send_clear.setObjectName("btn_send_clear")
        self.gridLayout.addWidget(self.btn_send_clear, 0, 0, 1, 1)
        self.btn_send_file = QtWidgets.QPushButton(self.frame_3)
        self.btn_send_file.setObjectName("btn_send_file")
        self.gridLayout.addWidget(self.btn_send_file, 1, 0, 1, 1)
        self.btn_send_save = QtWidgets.QPushButton(self.frame_3)
        self.btn_send_save.setObjectName("btn_send_save")
        self.gridLayout.addWidget(self.btn_send_save, 0, 1, 1, 1)
        self.chk_autosend = QtWidgets.QCheckBox(self.frame_3)
        self.chk_autosend.setObjectName("chk_autosend")
        self.gridLayout.addWidget(self.chk_autosend, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.txt_send_period = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_send_period.sizePolicy().hasHeightForWidth())
        self.txt_send_period.setSizePolicy(sizePolicy)
        self.txt_send_period.setMinimumSize(QtCore.QSize(50, 0))
        self.txt_send_period.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_send_period.setObjectName("txt_send_period")
        self.horizontalLayout_10.addWidget(self.txt_send_period)
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.gridLayout.addLayout(self.horizontalLayout_10, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame_3)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.txt_recv = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txt_recv.setObjectName("txt_recv")
        self.verticalLayout_4.addWidget(self.txt_recv)
        self.frame_5 = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 75))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_6.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.radio_recv_text_mode = QtWidgets.QRadioButton(self.frame_6)
        self.radio_recv_text_mode.setObjectName("radio_recv_text_mode")
        self.verticalLayout_10.addWidget(self.radio_recv_text_mode)
        self.radio_recv_hex_mode = QtWidgets.QRadioButton(self.frame_6)
        self.radio_recv_hex_mode.setObjectName("radio_recv_hex_mode")
        self.verticalLayout_10.addWidget(self.radio_recv_hex_mode)
        self.radio_recv_doublebyte = QtWidgets.QRadioButton(self.frame_6)
        self.radio_recv_doublebyte.setObjectName("radio_recv_doublebyte")
        self.verticalLayout_10.addWidget(self.radio_recv_doublebyte)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.horizontalLayout_8.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_recv_clear = QtWidgets.QPushButton(self.frame_7)
        self.btn_recv_clear.setObjectName("btn_recv_clear")
        self.gridLayout_3.addWidget(self.btn_recv_clear, 0, 0, 1, 1)
        self.btn_recv_save = QtWidgets.QPushButton(self.frame_7)
        self.btn_recv_save.setObjectName("btn_recv_save")
        self.gridLayout_3.addWidget(self.btn_recv_save, 1, 0, 1, 1)
        self.btn_recv_copy = QtWidgets.QPushButton(self.frame_7)
        self.btn_recv_copy.setObjectName("btn_recv_copy")
        self.gridLayout_3.addWidget(self.btn_recv_copy, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.frame_7)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lbl_state = QtWidgets.QLabel(self.centralwidget)
        self.lbl_state.setText("")
        self.lbl_state.setObjectName("lbl_state")
        self.verticalLayout.addWidget(self.lbl_state)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "ComHelper", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "串口名", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "波特率", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "字节位", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "校验", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "结束位", None, -1))
        self.btn_open.setText(QtWidgets.QApplication.translate("MainWindow", "打开", None, -1))
        self.btn_close.setText(QtWidgets.QApplication.translate("MainWindow", "关闭", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "发送", None, -1))
        self.radio_send_text_mode.setText(QtWidgets.QApplication.translate("MainWindow", "文本模式", None, -1))
        self.radio_send_hex_mode.setText(QtWidgets.QApplication.translate("MainWindow", "十六进制模式", None, -1))
        self.radio_send_doublebyte.setToolTip(QtWidgets.QApplication.translate("MainWindow", "比如发送单字符\'A\'，实际发送的是双字符\'41\'，\'A\'=0x41", None, -1))
        self.radio_send_doublebyte.setText(QtWidgets.QApplication.translate("MainWindow", "双字节", None, -1))
        self.btn_send_data.setText(QtWidgets.QApplication.translate("MainWindow", "发送数据", None, -1))
        self.btn_send_clear.setText(QtWidgets.QApplication.translate("MainWindow", "清空发送数据", None, -1))
        self.btn_send_file.setText(QtWidgets.QApplication.translate("MainWindow", "发送文件", None, -1))
        self.btn_send_save.setText(QtWidgets.QApplication.translate("MainWindow", "保存发送数据", None, -1))
        self.chk_autosend.setText(QtWidgets.QApplication.translate("MainWindow", "自动发送", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "周期", None, -1))
        self.txt_send_period.setText(QtWidgets.QApplication.translate("MainWindow", "1000", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "ms", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "接收", None, -1))
        self.radio_recv_text_mode.setText(QtWidgets.QApplication.translate("MainWindow", "文本模式", None, -1))
        self.radio_recv_hex_mode.setText(QtWidgets.QApplication.translate("MainWindow", "十六进制模式", None, -1))
        self.radio_recv_doublebyte.setToolTip(QtWidgets.QApplication.translate("MainWindow", "比如接收的是双字符\'41\'，转换成单字符\'A\', \'A\'=0x41", None, -1))
        self.radio_recv_doublebyte.setText(QtWidgets.QApplication.translate("MainWindow", "双字节", None, -1))
        self.btn_recv_clear.setText(QtWidgets.QApplication.translate("MainWindow", "清空接收区", None, -1))
        self.btn_recv_save.setText(QtWidgets.QApplication.translate("MainWindow", "保存接收数据", None, -1))
        self.btn_recv_copy.setText(QtWidgets.QApplication.translate("MainWindow", "复制接收数据", None, -1))

